name: main
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    steps:
    - uses: actions/checkout@v4
    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
    - run: deno task test --junit-path=.test-report.xml
    - uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: .test-report.xml
    - run: deno task check
